// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System.Reflection;

//
// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
//
[assembly: AssemblyCompany("Interstates Control Systems, Inc.")]
[assembly: AssemblyProduct("Control.Database")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCopyright("Copyright © Interstates Control Systems, Inc. 2007-2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

//
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
[assembly: AssemblyVersion("2.13.0.0")]
[assembly: AssemblyFileVersion("2.19.523.880")]
